# Site settings
title: Sahed Martinez
email: smarti28@u.rochester.edu
description: "My Website"
baseurl: /SahedM

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fefafb
  secondary: 1976d2
  secondary-dark: c82a40

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sahedd
  - title: github
    url: http://github.com/sahedd

# Postal address (add as many lines as necessary)
address:
  - line: Rochester
  - line: NY

# Build settings
markdown: kramdown
permalink: pretty
